#!/bin/sh
if test $# -lt 3
then
echo "usage: [path/to/build] [path/to/framework] [path/to/plugins] [options]"
echo "valid options are:"
echo "-m = use macdeployqt"
echo "-c = use install_name_tool"
else
#echo {$PWD}
#$CURRENTPATH = {$PWD}
#echo $CURRENTPATH 

cd $1

#------------------------------------
#finding the dependencies of the app:
#------------------------------------
otool -L PSndDemo.app/Contents/MacOS/PSndDemo

#--------------------------------
# making all necessary directories
#--------------------------------
mkdir PSndDemo.app/Contents/Frameworks
mkdir PSndDemo.app/Contents/Plugins
mkdir PSndDemo.app/Contents/doc
#mkdir PSndDemo.app/Contents/qss
#mkdir PSndDemo.app/Contents/images


#------------------------------
#copying the required Librarys
#not copied by macdeployqt:
#------------------------------
#cp /usr/local/lib/libmeta.dylib PSndDemo.app/Contents/Frameworks
cp  /Developer/SDKs/meta/x86/lib/libmeta.dylib PSndDemo.app/Contents/Frameworks
#cp /Developer/Qt_projekte/meta-build-desktop-Qt_aus_PATH_Release/libmeta.dylib PSndDemo.app/Contents/Frameworks 
cp  /usr/lib/libltdl.3.dylib PSndDemo.app/Contents/Frameworks

cp  /Developer/Qt_projekte/ProSoundFinder/qt.conf PSndDemo.app/Contents/Resources
cp  /Developer/Qt_projekte/ProSoundFinder/PSndDemo.icns PSndDemo.app/Contents/Resources
rm  PSndDemo.app/Contents/Info.plist
cp  /Developer/Qt_projekte/ProSoundFinder/Info.plist PSndDemo.app/Contents/Info.plist
cp  /Developer/Qt_projekte/ProSoundFinder/doc/HELP_PSndDemo.pdf PSndDemo.app/Contents/doc/HELP_PSndDemo.pdf


#------------------------------
#copying Special Case Old MySqlDriver
#not copied by macdeployqt:
#------------------------------
cp  /Developer/Applications/Qt/plugins/sqldrivers/libqsqlmysql.dylib PSndDemo.app/Contents/Plugins/sqldrivers




if test $# -gt 3
	then
	if test $4 = "-c"
	then
#------------------------------
#copying the required Librarys:
#------------------------------
#cp -R /Developer/SDKs/libsndfile/libsndfile_Universal/local/lib/libsndfile.1.dylib PSndDemo.app/Contents/Frameworks
#cp -R /Developer/SDKs/libsndfile/libsndfile_Universal/local/lib/libsndfile.dylib PSndDemo.app/Contents/Frameworks
cp  /Developer/SDKs/meta/x86/lib/libmeta.dylib PSndDemo.app/Contents/Frameworks
cp -R /Developer/SDKs/libmp123/x86/lib/libmpg123.dylib PSndDemo.app/Contents/Frameworks
cp -R /Developer/SDKs/libmp123/x86/lib/libmpg123.0.dylib PSndDemo.app/Contents/Frameworks


#--------------------------------
#copying the required Frameworks:
#--------------------------------
cp -R $2/QtGui.framework PSndDemo.app/Contents/Frameworks
cp -R $2/phonon.framework PSndDemo.app/Contents/Frameworks
cp -R $2/QtCore.framework PSndDemo.app/Contents/Frameworks
cp -R $2/QtSql.framework PSndDemo.app/Contents/Frameworks
cp -R $2/QtNetwork.framework PSndDemo.app/Contents/Frameworks
cp -R $2/QtOpenGL.framework PSndDemo.app/Contents/Frameworks
cp -R $2/QtDBus.framework PSndDemo.app/Contents/Frameworks

#-----------------------------
#copying the required Plugins:
#-----------------------------
cp -R $3/sqldrivers PSndDemo.app/Contents/Plugins
#cp -R $3/phonon_backend PSndDemo.app/Contents/Plugins
cp -R $3 PSndDemo.app/Contents

#-----------------------------
#copying other required Stuff:
#-----------------------------
#cp -R /Developer/Qt_projekte/ProSoundFinder/doc PSndDemo.app/Contents/doc
#cp -R /Developer/Qt_projekte/ProSoundFinder/qss PSndDemo.app/Contents/qss
#cp -R /Developer/Qt_projekte/ProSoundFinder/images PSndDemo.app/Contents/images
#cp -R /Developer/Qt_projekte/ProSoundFinder/PSndDemo.icns PSndDemo.app/Contents/Resources




#-------------------
#changing the names:
#-------------------

install_name_tool -id @executable_path/../Frameworks/QtGui.framework/Versions/4.0/QtGui PSndDemo.app/Contents/Frameworks/QtGui.framework/Versions/4/QtGui
install_name_tool -id @executable_path/../Frameworks/QtCore.framework/Versions/4.0/QtCore PSndDemo.app/Contents/Frameworks/QtCore.framework/Versions/4/QtCore
install_name_tool -id @executable_path/../Frameworks/phonon.framework/Versions/4.0/phonon PSndDemo.app/Contents/Frameworks/phonon.framework/Versions/4/phonon
install_name_tool -id @executable_path/../Frameworks/QtSql.framework/Versions/4.0/QtSql PSndDemo.app/Contents/Frameworks/QtSql.framework/Versions/4/QtSql
install_name_tool -id @executable_path/../Frameworks/QtNetwork.framework/Versions/4.0/QtNetwork PSndDemo.app/Contents/Frameworks/QtNetwork.framework/Versions/4/QtNetwork
install_name_tool -id @executable_path/../Frameworks/QtOpenGL.framework/Versions/4.0/QtOpenGL PSndDemo.app/Contents/Frameworks/QtOpenGL.framework/Versions/4/QtOpenGL
install_name_tool -id @executable_path/../Frameworks/QtDBus.framework/Versions/4.0/QQtDBus PSndDemo.app/Contents/Frameworks/QtDBus.framework/Versions/4/QtDBus

install_name_tool -id @executable_path/../Frameworks/libmeta.dylib PSndDemo.app/Contents/Frameworks/libmeta.dylib
install_name_tool -id @executable_path/../Frameworks/libmpg123.0.dylib PSndDemo.app/Contents/Frameworks/libmpg123.0.dylib
install_name_tool -id @executable_path/../Frameworks/libsndfile.dylib PSndDemo.app/Contents/Frameworks/libsndfile.dylib

#-------------------------------------------------------------
#changing the dependencies of the app:
#zuerst kommt der alte Pfad der zu findenden Library, 
#dann der neue Pfad der zu findenden Library 
#und dann die bin oder Lib die nach der zu findenden Lib sucht!!
# the following leeds to duplicate declarations:
#--------------------------------------------------------------

#echo "changing "$2"/QtCore.framework/Versions/4/QtCore"
#install_name_tool -change $2/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore PSndDemo.app/Contents/MacOs/PSndDemo

#echo "changing "$2"/QtCore.framework/Versions/4/QtGui"
#install_name_tool -change $2/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui PSndDemo.app/Contents/MacOs/PSndDemo

#echo "changing "$2"/QtCore.framework/Versions/4/phonon"
#install_name_tool -change $2/phonon.framework/Versions/4/phonon @executable_path/../Frameworks/phonon.framework/Versions/4/phonon PSndDemo.app/Contents/MacOs/PSndDemo

#echo "changing "$2"/QtCore.framework/Versions/4/QtSql"
#install_name_tool -change $2/QtSql.framework/Versions/4/QtSql @executable_path/../Frameworks/QtSql.framework/Versions/4/QtSql PSndDemo.app/Contents/MacOs/PSndDemo

#echo "changing "$2"/QtCore.framework/Versions/4/QtNetwork"
#install_name_tool -change $2/QtNetwork.framework/Versions/4/QtNetwork @executable_path/../Frameworks/QtNetwork.framework/Versions/4/QtNetwork PSndDemo.app/Contents/MacOs/PSndDemo

install_name_tool -change /usr/local/lib/libsndfile.1.dylib @executable_path/../Frameworks/libsndfile.dylib PSndDemo.app/Contents/MacOs/PSndDemo
install_name_tool -change /usr/local/lib/libmpg123.0.dylib @executable_path/../Frameworks/libmpg123.0.dylib PSndDemo.app/Contents/MacOs/PSndDemo
install_name_tool -change //usr/local/lib/libmeta.dylib @executable_path/../Frameworks/libmeta.dylib PSndDemo.app/Contents/MacOs/PSndDemo


#--------------------------------------
#changing dependencies of the Libraries:
#---------------------------------------

	
#install_name_tool -change $2/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui PSndDemo.app/Contents/Frameworks/QtGui.framework/#Versions/4/QtGui

install_name_tool -change $2/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore PSndDemo.app/Contents/Frameworks/QtGui.framework/Versions/4/QtGui
install_name_tool -change $2/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore PSndDemo.app/Contents/Frameworks/phonon.framework/Versions/4/phonon
install_name_tool -change $2/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore PSndDemo.app/Contents/Frameworks/QtNetwork.framework/Versions/4/QtNetwork
install_name_tool -change $2/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore PSndDemo.app/Contents/Frameworks/QtSql.framework/Versions/4/QtSql
install_name_tool -change $2/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore PSndDemo.app/Contents/Frameworks/QtOpenGL.framework/Versions/4/QtOpenGL
install_name_tool -change $2/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore PSndDemo.app/Contents/Frameworks/QtDBus.framework/Versions/4/QtDBus
install_name_tool -change $2/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore PSndDemo.app/Contents/Frameworks/QtXml.framework/Versions/4/QtXml
#install_name_tool -change $2QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore PSndDemo.app/Contents/Frameworks/libsndfile.1.dylib
#install_name_tool -change /Developer/SDKs/meta/x86/lib/libmeta.dylib @executable_path/../Frameworks/libmeta.dylib PSndDemo.app/Contents/MacOs/PSndDemo.app/Contents/Frameworks/QtGui.framework/Versions/4/QtGui
#install_name_tool -change /Developer/SDKs/meta/x86/lib/libmeta.dylib @executable_path/../Frameworks/libmeta.dylib PSndDemo.app/Contents/MacOs/PSndDemo.app/Contents/Frameworks/QtCore.framework/Versions/4/QtCore



install_name_tool -change $2/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui PSndDemo.app/Contents/Frameworks/phonon.framework/Versions/4/phonon
install_name_tool -change $2/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtCore PSndDemo.app/Contents/Frameworks/QtOpenGL.framework/Versions/4/QtOpenGL
install_name_tool -change $2/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui PSndDemo.app/Contents/Frameworks/QtDBus.framework/Versions/4/QtDBus
install_name_tool -change $2/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui PSndDemo.app/Contents/Frameworks/QtOpenGL.framework/Versions/4/QtOpenGL
install_name_tool -change $2/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui PSndDemo.app/Contents/Frameworks/QtSql.framework/Versions/4/QtSql
install_name_tool -change $2/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui PSndDemo.app/Contents/Frameworks/QtXml.framework/Versions/4/QtXml
#install_name_tool -change $2/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui PSndDemo.app/Contents/Frameworks/libsndfile.1.dylib

#otool -L PSndDemo.app/Contents/MacOS/PSndDemo
fi
fi


if test $# -gt 3
	then
	if test $4 = "-m"
		then
		macdeployqt  PSndDemo.app
		echo "tool after running macdeployqt:"
		otool -L PSndDemo.app/Contents/MacOS/PSndDemo
		fi

	fi

#--------------------------------
#changing the dependencies of the 
#app not changed by macdeployqt:
#--------------------------------
#echo "changing /Developer/SDKs/meta/x86/lib/libmeta.dylib"
#install_name_tool -change /Developer/SDKs/meta/x86/lib/libmeta.dylib @executable_path/../Frameworks/libmeta.dylib PSndDemo.app/Contents/MacOs/PSndDemo
#install_name_tool -change /Developer/Qt_projekte/meta-build-desktop-Qt_aus_PATH_Release/libmeta.dylib @executable_path/../Frameworks/libmeta.dylib PSndDemo.app/Contents/MacOs/PSndDemo

install_name_tool -change /usr/lib/libltdl.3.dylib @executable_path/../Frameworks/libltdl.3.dylib PSndDemo.app/Contents/Frameworks/libmpg123.0.dylib
#install_name_tool -change //usr/local/lib/libmeta.dylib @executable_path/../Frameworks/libmeta.dylib PSndDemo.app/Contents/MacOs/QtCore
#install_name_tool -change //usr/local/lib/libmeta.dylib @executable_path/../Frameworks/libmeta.dylib PSndDemo.app/Contents/MacOs/PSndDemo



#-----------------------------------------------
#remove the unused stuff created by macdeployqt:
#-----------------------------------------------
rm PSndDemo.app/Contents/Plugins/sqldrivers/libqsqlite_debug.dylib
rm PSndDemo.app/Contents/Plugins/sqldrivers/libqsqlodbc_debug.dylib
rm PSndDemo.app/Contents/Plugins/phonon_backend/libphonon_qt7_debug.dylib
rm -rf PSndDemo.app/Contents/Plugins/phonon_backend/libphonon_qt7_debug.dSYM

rm -rf PSndDemo.app/Contents/Plugins/designer
rm -rf PSndDemo.app/Contents/Plugins/iconengines
rm -rf PSndDemo.app/Contents/Plugins/accessible
rm -rf PSndDemo.app/Contents/Plugins/bearer
rm -rf PSndDemo.app/Contents/Plugins/codecs
rm -rf PSndDemo.app/Contents/Plugins/graphicssystems
rm -rf PSndDemo.app/Contents/Plugins/imageformats
rm -rf PSndDemo.app/Contents/Plugins/qmltooling


rm PSndDemo.app/Contents/Frameworks/phonon.framework/Versions/4/phonon_debug
rm PSndDemo.app/Contents/Frameworks/phonon.framework/phonon_debug
rm PSndDemo.app/Contents/Frameworks/phonon.framework/phonon_debug.prl
rm -rf PSndDemo.app/Contents/Frameworks/phonon.framework/phonon_debug.dSYM


rm PSndDemo.app/Contents/Frameworks/QtCore.framework/Versions/4/QtCore_debug
rm PSndDemo.app/Contents/Frameworks/QtCore.framework/QtCore_debug
rm PSndDemo.app/Contents/Frameworks/QtCore.framework/QtCore_debug.prl
rm -rf PSndDemo.app/Contents/Frameworks/QtCore.framework/QtCore_debug.dSYM


rm PSndDemo.app/Contents/Frameworks/QtGui.framework/Versions/4/QtGui_debug
rm PSndDemo.app/Contents/Frameworks/QtGui.framework/QtGui_debug
rm PSndDemo.app/Contents/Frameworks/QtGui.framework/QtGui_debug.prl
rm -rf PSndDemo.app/Contents/Frameworks/QtGui.framework/QtGui_debug.dSYM

rm PSndDemo.app/Contents/Frameworks/QtNetwork.framework/Versions/4/QtNetwork_debug
rm PSndDemo.app/Contents/Frameworks/QtNetwork.framework/QtNetwork_debug
rm PSndDemo.app/Contents/Frameworks/QtNetwork.framework/QtNetwork_debug.prl
rm -rf PSndDemo.app/Contents/Frameworks/QtNetwork.framework/QtNetwork_debug.dSYM

rm PSndDemo.app/Contents/Frameworks/QtSql.framework/Versions/4/QtSql_debug
rm PSndDemo.app/Contents/Frameworks/QtSql.framework/QtSql_debug
rm PSndDemo.app/Contents/Frameworks/QtSql.framework/QtSql_debug.prl
rm -rf PSndDemo.app/Contents/Frameworks/QtSql.framework/QtSql_debug.dSYM

rm PSndDemo.app/Contents/Frameworks/QtOpenGL.framework/Versions/4/QtOpenGL_debug
rm PSndDemo.app/Contents/Frameworks/QtOpenGLl.framework/QtOpenGL_debug
rm PSndDemo.app/Contents/Frameworks/QtOpenGL.framework/QtOpenGL_debug.prl
rm -rf PSndDemo.app/Contents/Frameworks/QtOpenGL.framework/QtOpenGL_debug.dSYM

rm PSndDemo.app/Contents/Frameworks/QtDBus.framework/Versions/4/QtDBus_debug
rm PSndDemo.app/Contents/Frameworks/QtDBus.framework/QtDBus_debug
rm PSndDemo.app/Contents/Frameworks/QtDBus.framework/QtDBus_debug.prl
rm -rf PSndDemo.app/Contents/Frameworks/QtDBus.framework/QtDBus_debug.dSYM

rm -rf PSndDemo.app/Contents/Frameworks/QtDeclarative.framework
rm -rf PSndDemo.app/Contents/Frameworks/QtScript.framework
rm -rf PSndDemo.app/Contents/Frameworks/QtSvg.framework
rm -rf PSndDemo.app/Contents/Frameworks/QtXmlPatterns.framework



echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+++++++++++++++++++++ Testing Library Debendencys +++++++++++++++++++++++++++++++++++++++++++"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "PSndDemo"
otool -L PSndDemo.app/Contents/MacOS/PSndDemo
echo "libmeta"
otool -L PSndDemo.app/Contents/Frameworks/libmeta.dylib
echo "libmpg123.0"
otool -L PSndDemo.app/Contents/Frameworks/libmpg123.0.dylib
echo "libsndfile:"
otool -L PSndDemo.app/Contents/Frameworks/libsndfile.1.dylib
echo "phonon:"
otool -L PSndDemo.app/Contents/Frameworks/phonon.framework/Versions/4/phonon
echo "QtCore:"
otool -L PSndDemo.app/Contents/Frameworks/QtCore.framework/Versions/4/QtCore
echo "QtGui"
otool -L PSndDemo.app/Contents/Frameworks/QtGui.framework/Versions/4/QtGui
echo "QtNetwork:"
otool -L PSndDemo.app/Contents/Frameworks/QtNetwork.framework/Versions/4/QtNetwork
echo "QtOpenGL:"
otool -L PSndDemo.app/Contents/Frameworks/QtOpenGL.framework/Versions/4/QtOpenGL
echo "QtSql:"
otool -L PSndDemo.app/Contents/Frameworks/QtSql.framework/Versions/4/QtSql



fi

cd $PWD
