#############################################################################
# Makefile for building: PSndDemo.app/Contents/MacOS/PSndDemo
# Generated by qmake (2.01a) (Qt 4.8.5) on: Thu Sep 19 17:45:17 2013
# Project:  PSndDemo.pro
# Template: app
# Command: /Developer/Qt4.8.5/qt-qt/bin/qmake -spec /usr/local/Trolltech/Qt-4.8.5/mkspecs/macx-g++42 CONFIG+=x86 CONFIG+=declarative_debug -o Makefile PSndDemo.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc-4.2
CXX           = g++-4.2
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -mmacosx-version-min=10.5 -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.5/mkspecs/macx-g++42 -I. -I/usr/local/Trolltech/Qt-4.8.5/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.8.5/include/QtCore -I/usr/local/Trolltech/Qt-4.8.5/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.8.5/include/QtGui -I/usr/local/Trolltech/Qt-4.8.5/include -I../../SDKs/libsndfile/libsndfile_86_10.5/local/include -I../PSndWave -I../PSndWave/QWave2 -I../PSndPlayer -I. -I/usr/local/include -I. -F/usr/local/Trolltech/Qt-4.8.5/lib
LINK          = g++-4.2
LFLAGS        = -headerpad_max_install_names -F/System/Library/Frameworks -F//Developer/Library/PrivateFrameworks -arch i386
LIBS          = $(SUBLIBS) -F/usr/local/Trolltech/Qt-4.8.5/lib -L/usr/local/Trolltech/Qt-4.8.5/lib -L/Developer/Qt_Projekte/PSndWave-build-Desktop_GCC_x86_32bit-Debug -L/Developer/Qt_Projekte/PSndPlayer-build-Desktop_GCC_x86_32bit-Debug -L/Developer/SDKs/libmp123/x86/lib -L/Developer/SDKs/meta/x86/lib -L/Developer/SDKs/libsndfile/libsndfile_86_10.5/local/lib -lsndfile -lPSndPlayer -lPSndWave -framework QtGui -L/usr/local/Trolltech/Qt-4.8.5/lib -F/usr/local/Trolltech/Qt-4.8.5/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Developer/Qt4.8.5/qt-qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.5

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qwave2.cc moc_qwave2.cpp
OBJECTS       = qwave2.o \
		moc_qwave2.o
DIST          = /usr/local/Trolltech/Qt-4.8.5/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/g++-macx.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/x86.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/declarative_debug.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/rez.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/include_source_dir.prf \
		PSndDemo.pro
QMAKE_TARGET  = PSndDemo
DESTDIR       = 
TARGET        = PSndDemo.app/Contents/MacOS/PSndDemo

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		i386 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile PSndDemo.app/Contents/PkgInfo PSndDemo.app/Contents/Resources/empty.lproj PSndDemo.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) PSndDemo.app/Contents/MacOS/ || $(MKDIR) PSndDemo.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PSndDemo.pro  /usr/local/Trolltech/Qt-4.8.5/mkspecs/macx-g++42/qmake.conf /usr/local/Trolltech/Qt-4.8.5/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/g++-macx.conf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/x86.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/declarative_debug.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/rez.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.5/lib/QtGui.framework/QtGui.prl \
		/usr/local/Trolltech/Qt-4.8.5/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.5/mkspecs/macx-g++42 CONFIG+=x86 CONFIG+=declarative_debug -o Makefile PSndDemo.pro
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/mac.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/gcc-base-macx.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/common/g++-macx.conf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/dwarf2.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/default_post.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/x86.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/objective_c.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/declarative_debug.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/rez.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/mac/sdk.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.5/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.5/lib/QtGui.framework/QtGui.prl:
/usr/local/Trolltech/Qt-4.8.5/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.5/mkspecs/macx-g++42 CONFIG+=x86 CONFIG+=declarative_debug -o Makefile PSndDemo.pro

PSndDemo.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) PSndDemo.app/Contents || $(MKDIR) PSndDemo.app/Contents 
	@$(DEL_FILE) PSndDemo.app/Contents/PkgInfo
	@echo "APPL????" >PSndDemo.app/Contents/PkgInfo
PSndDemo.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) PSndDemo.app/Contents/Resources || $(MKDIR) PSndDemo.app/Contents/Resources 
	@touch PSndDemo.app/Contents/Resources/empty.lproj
	
PSndDemo.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) PSndDemo.app/Contents || $(MKDIR) PSndDemo.app/Contents 
	@$(DEL_FILE) PSndDemo.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,PSndDemo,g" -e "s,@TYPEINFO@,????,g" /usr/local/Trolltech/Qt-4.8.5/mkspecs/macx-g++42/Info.plist.app >PSndDemo.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/PSndDemo1.0.0 || $(MKDIR) .tmp/PSndDemo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/PSndDemo1.0.0/ && $(COPY_FILE) --parents qwave2.h .tmp/PSndDemo1.0.0/ && $(COPY_FILE) --parents qwave2.cc .tmp/PSndDemo1.0.0/ && (cd `dirname .tmp/PSndDemo1.0.0` && $(TAR) PSndDemo1.0.0.tar PSndDemo1.0.0 && $(COMPRESS) PSndDemo1.0.0.tar) && $(MOVE) `dirname .tmp/PSndDemo1.0.0`/PSndDemo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/PSndDemo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r PSndDemo.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_qwave2.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qwave2.cpp
moc_qwave2.cpp: qwave2.h
	/usr/local/Trolltech/Qt-4.8.5/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ qwave2.h -o moc_qwave2.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

qwave2.o: qwave2.cc qwave2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qwave2.o qwave2.cc

moc_qwave2.o: moc_qwave2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qwave2.o moc_qwave2.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

